server:
  port: 8888

spring:
  application:
    name: poti-monitor
  boot:
    admin:
      ui:
        title: 破题监控中心
      discovery:
        enabled: true
        ignored-services: poti-monitor
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.codecentric.boot.admin: debug
